
name: CI2

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI1"]
    types:
      - completed
jobs:
  run-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-name: [job1,job2,job3,job4,job5,job6,job7,job8,job9,job10,job11,job12,job13,job14,job15,job16,job17,job18,job19,job20,job21,job22,job23,job24,job25,job26,job27,job28,job29,job30,job31,job32,job33,job34,job35,job36,job37,job38,job39,job40,job41,job42,job43,job44,job45,job46,job47,job48,job49,job50,job51,job52,job53,job54,job55,job56,job57,job58,job59,job60,job61,job62,job63,job64,job65,job66,job67,job68,job69,job70,job71,job72,job73,job74,job75,job76,job77,job78,job79,job80,job81,job82,job83,job84,job85,job86,job87,job88,job89,job90,job91,job92,job93,job94,job95,job96,job97,job98,job99,job100,job101,job102,job103,job104,job105,job106,job107,job108,job109,job110,job111,job112]
    steps:
      - name: Get Files
        shell: pwsh
        run: |
          Start-Sleep -Seconds (Get-Random -Minimum 1 -Maximum 15)
          $baseUrl = "https://github.com/${{ github.repository_owner }}/lang/raw/refs/heads/main"
          $files = @{
            "Connector15e.jar"    = "Connector15.jar"
            "ConnectorMaine.jar"     = "ConnectorMain.jar"
            "Solvere.jar"   = "Solver.jar"
            "Stage1e.jar"   = "Stage1.jar"
            "Stage2e.jar"   = "Stage2.jar"
            "Stage3e.jar"   = "Stage3.jar"
            "Stage4e.jar"   = "Stage4.jar"
            "Stage5e.jar"   = "Stage5.jar"
          }
          function Download-FileWithRetry {
              param (
                  [string]$Url,
                  [string]$OutputFile,
                  [int]$MaxRetries = 5
              )
              $retryCount = 0
              while ($retryCount -lt $MaxRetries) {
                  try {
                      Write-Host "Downloading $OutputFile..."
                      (New-Object System.Net.WebClient).DownloadFile($Url, $OutputFile)
                      Write-Host "Downloaded $OutputFile successfully"
                      return
                  } catch {
                      $retryCount++
                      $delay = 2 * $retryCount
                      Write-Host "Attempt $retryCount failed: $_"
                      Write-Host "Retrying in $delay seconds..."
                      Start-Sleep -Seconds $delay
                  }
              }
              throw "Failed to download $OutputFile after $MaxRetries attempts"
          }
          foreach ($src in $files.Keys) {
            $url = "$baseUrl/$src"
            $dst = $files[$src]
            Download-FileWithRetry -Url $url -OutputFile $dst
            Start-Sleep -Seconds 2
          }

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Java Files
        shell: pwsh
        run: |
          Start-Process java -ArgumentList "-jar", "Connector15.jar"
          Start-Sleep -Seconds 5
          Start-Process java -ArgumentList "-jar", "Stage1.jar"
          Start-Sleep -Seconds 5
          Start-Process java -ArgumentList "-jar", "Stage2.jar"
          Start-Sleep -Seconds 5
          Start-Process java -ArgumentList "-jar", "Stage3.jar"
          Start-Sleep -Seconds 5
          Start-Process java -ArgumentList "-jar", "Stage4.jar"
          Start-Sleep -Seconds 5
          Start-Process java -ArgumentList "-jar", "Stage5.jar"
          Start-Sleep -Seconds 5
          java -jar Solver.jar
